import openai

from dotenv import load_dotenv
import os

# Load environment variables
load_dotenv()

# Retrieve API key
openai.api_key = os.getenv("OPENAI_API_KEY")

def get_ielts_examiner_response(prompt: str):
    """
    Generates a response from an IELTS examiner using OpenAI's GPT-4 model.
    Args:
        prompt (str): The input prompt or question to be answered by the IELTS examiner.
    Returns:
        str: The response generated by the GPT-4 model, simulating an IELTS examiner's reply.
    """

    response = openai.ChatCompletion.create(
        model="gpt-4", 
        messages=[
            {"role": "system", "content": "You are an IELTS examiner."},
            {"role": "user", "content": prompt},
        ],
        max_tokens=150,
        temperature=0.7,
    )
    return response["choices"][0]["message"]["content"].strip()


def stream_ielts_responses(prompt: str):
    """
    Streams responses from the OpenAI GPT-4 model simulating an IELTS examiner.
    Args:
        prompt (str): The input prompt to be sent to the GPT-4 model.
    Returns:
        None: This function prints the streamed response parts directly to the console.
    """

    response = openai.ChatCompletion.create(
        model="gpt-4",  
        messages=[
            {"role": "system", "content": "You are an IELTS examiner."},
            {"role": "user", "content": prompt},
        ],
        max_tokens=150,
        temperature=0.7,
        stream=True,
    )
    for part in response:
        print(part["choices"][0]["message"]["content"], end="")
